name: CI

concurrency:
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  doc:
    env:
      FORCE_COLOR: 1
    name: Execute and build documentation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      - name: Fetch caches
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: |
            quarto-cache-${{ hashFiles('uv.lock') }}-${{ hashFiles('docs/**') }}
          restore-keys: |
            quarto-cache-${{ hashFiles('uv.lock') }}
          path: |
            ./docs/.jupyter_cache/
            ./docs/.quarto/
            ./docs/images/chapter2/riemann-surface.png
            ./docs/output/
      - name: Install Graphviz and SVG converter
        run: |
          sudo apt-get update --yes
          sudo apt-get install graphviz librsvg2-bin --yes
      - name: Install TinyTex
        run: |
          uv run quarto install tinytex --update-path
          tlmgr install cm-super type1cm underscore
      - name: Build documentation
        run: uvx --from poethepoet poe doc
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: docs/_build/html

  gh-pages:
    name: Upload to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: [doc]
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
